In [309]:
import numpy as np

In [310]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [311]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [312]:
# Get Dimension
b.ndim

2

In [313]:
# Get Shape
b.shape

(2, 3)

In [314]:
#reshape
x = np.array([1,2,3,4,5,6])
print(x)

y= x.reshape(3,2)
print(y)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [315]:
y= x.reshape(6,1)
print(y)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [316]:
# Get Type
b.dtype

dtype('float64')

In [317]:
# Get Size
b.itemsize

8

In [318]:
# Get total size
b.nbytes

48

In [319]:
# Get number of elements
b.size

6

### Accessing/Changing Specific Elements, Rows, Columns, etc¶

In [320]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [321]:
# Get a specific element [r, c]
a[1,5]

13

In [322]:
# Get a specific row 
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [323]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [324]:
# [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [325]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [326]:
# Update an element

a[1,5] = 27
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 27 14]]


In [327]:
# Update elements
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 27 14]]


In [328]:
a[1,:]=21
print(a)

[[ 1  2  5  4  5  6  7]
 [21 21 21 21 21 21 21]]


In [329]:
# Update elements
a[:,2] = [18,19]
print(a)

[[ 1  2 18  4  5  6  7]
 [21 21 19 21 21 21 21]]


### 3-D Array

In [330]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [331]:
print(b[0,:,:])

[[1 2]
 [3 4]]


### Initializing Different Types of Arrays

In [343]:
# All 0s matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [344]:
np.zeros((2,3,3), dtype='int32')

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [333]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [334]:
# Any other number
np.full((2,2), 27)

array([[27, 27],
       [27, 27]])

In [335]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [336]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.0323053 , 0.06860532],
       [0.40391049, 0.45495203],
       [0.0869293 , 0.60288885],
       [0.14949693, 0.38370447]])

In [347]:
# Random Integer values
np.random.randint(-4, 12, size=(3,3))

array([[-1, 11, -2],
       [11,  7,  9],
       [10, -2,  4]])

In [338]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Copy and Other Operations

In [339]:
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)

[100   2   3]


In [340]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)
print(a)

[100   2   3]
[1 2 3]


In [348]:
%timeit a

60.2 ns ± 11.6 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
