### Arithmetic Operations on Numpy Array

In [29]:
import numpy as np

In [30]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [31]:
a+2

array([3, 4, 5, 6])

In [32]:
array1 = a-2
print(array1)

[-1  0  1  2]


In [33]:
a*2

array([2, 4, 6, 8])

In [34]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [35]:
a**2

array([ 1,  4,  9, 16])

In [36]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [37]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [38]:
# Trigonometric functions
np.sin(a[0])

0.8414709848078965

In [39]:
# More Funtions on Numpy array
# https://numpy.org/doc/stable/reference/routines.math.html

### Linear Algebra

In [40]:
a = np.array([[1,2,3,4],[8,9,10,11]])

b = np.array([[4,1],[5,3],[6,8],[3,2]])

#Matrix Multiplication:
np.matmul(a,b)

array([[ 44,  39],
       [170, 137]])

In [41]:
# Determinant of a matrix
a = np.array([[1,2,6],[7,8,9],[4,5,6]])
np.linalg.det(a)

8.999999999999998

In [42]:
#Eigen Value of square matrix
a = np.array([[1,6],[8,9]])
np.linalg.eig(a)

(array([-3., 13.]),
 array([[-0.83205029, -0.4472136 ],
        [ 0.5547002 , -0.89442719]]))

In [43]:
# For More linalg functions:
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html


# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [44]:
a = np.array([[3,6,2],[4,5,1]])
a

array([[3, 6, 2],
       [4, 5, 1]])

In [45]:
# Find minimum
np.min(a)

1

In [46]:
# Row wise min
np.min(a, axis=1)

array([2, 1])

In [47]:
# Column wise min
np.min(a, axis=0)

array([3, 5, 1])

In [48]:
# Similarly Max
np.max(a, axis=0)

array([4, 6, 2])

In [49]:
# Sum of elements
np.sum(a)

21

In [50]:
np.sum(a, axis = 0)

array([ 7, 11,  3])

In [51]:
# mean
a = np.array([[1,6,9],[4,5,1]])
np.mean(a)

4.333333333333333

In [52]:
# median
np.median(a)

4.5

In [53]:
# standard deviation
np.std(a)

2.8087165910587863

In [54]:
# Variation
np.var(a)

7.888888888888889

#### Linear Equations
    # 4x + 5y = 13
    # 5x - 3y = 7

In [55]:
coeff1 = np.array([[4,5],[5,-3]])
coeff2 = np.array([13,7])

np.linalg.solve(coeff1, coeff2)

array([2., 1.])

In [56]:
# More Statistical Funcions

# https://numpy.org/doc/stable/reference/routines.statistics.html